// src/pages/Calendar.jsx
import { useState, useEffect } from 'react'
import ReactCalendar from 'react-calendar'
import 'react-calendar/dist/Calendar.css'
import './Calendar.css'

export default function CalendarPage() {
  const [ayaats, setAyaats] = useState([])
  const [date, setDate] = useState(new Date())

  useEffect(() => {
    const modules = import.meta.glob('../assets/surah/surah_*.json')
    const load = async () => {
      const events = []
      const year = new Date().getFullYear()
      for (let i = 1; i <= 12; i++) {
        const mod = await modules[`../assets/surah/surah_${i}.json`]()
        const element = mod.default
        for (let j = 1; j < element.count && j <= 12; j++) {
          events.push({
            date: new Date(year, j - 1, i),
            title: element.verse[`verse_${j}`],
            num: `[${i}:${j}]`
          })
        }
        for (let j = 1; j < element.count && j <= 31; j++) {
          events.push({
            date: new Date(year, i - 1, j),
            title: element.verse[`verse_${j}`],
            num: `[${i}:${j}]`
          })
        }
      }
      events.sort((a,b)=>a.date-b.date)
      setAyaats(events)
    }
    load()
  }, [])

  const eventsByDate = ayaats.reduce((acc, ayah) => {
    const key = ayah.date.toISOString().slice(0,10)
    acc[key] = acc[key] || []
    acc[key].push(ayah)
    return acc
  }, {})

  const tileContent = ({ date: d, view }) => {
    const key = d.toISOString().slice(0,10)
    if (view === 'month' && eventsByDate[key]) {
      return <div className="highlight" />
    }
  }

  return (
    <div className="about">
      <ReactCalendar onChange={setDate} value={date} tileContent={tileContent} />
      <div className="events-wrapper">
        {(eventsByDate[date.toISOString().slice(0,10)] || []).map((ayah, idx) => (
          <div key={idx} className="event-item">
            <div className="wrapper">
              <h3 className="title">{ayah.title} <small>{ayah.num}</small></h3>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// src/views/Calendar.vue
<template>
  <div class="about">
    <vue-event-calendar v-if="eventsLoaded" :events="Ayaat">
      <template slot-scope="props">
        <div v-for="(ayah, index) in props.showEvents" :key="index" class="event-item">
          <div class="wrapper">
            <h3 class="title">{{ayah.title}} <small>{{ayah.num}}</small> </h3>
            <p class="time">{{ayah.date.slice(0,ayah.date.length-1)}}</p>
            <!-- <p class="desc"></p> -->
          </div>
        </div>
      </template>
    </vue-event-calendar>
  </div>

</template>

<script>
export default {
  components: {},
  data() {
    return {
      Ayaat: [],
      eventsLoaded: false
    };
  },
  created() {
    for (let surah = 1; surah <= 12; surah++) {
      const element = require(`../assets/surah/surah_${surah}.json`);
      for (let i = 1; i < element.count && i <= 12; i++) {
        this.Ayaat.push({
          date: `2019/${i}/${surah}/`,
          title: element.verse["verse_" + i],
          num:` [${surah}:${i}]`,

          customClass: "highlight"
        });
      }
      for (let i = 1; i < element.count && i <= 31; i++) {
        this.Ayaat.push({
          date: `2019/${surah}/${i}/`,
          title: element.verse["verse_" + i],
          num:` [${surah}:${i}]`,
          customClass: "highlight"
        });
      }
    }
    this.Ayaat.sort((a, b) => {
      return a > b ? 1 : a < b ? -1 : 0;
    });
    this.eventsLoaded = true;
  }
};
</script>

<style>

.__vev_calendar-wrapper .cal-wrapper .cal-body .dates .item .is-today {
  border-radius: 0% !important;
  background-color: #3c705de8 !important;
  color: #3c705de8;
  height: 3px;
}
.__vev_calendar-wrapper .events-wrapper .event-item .title {
  direction: rtl;
  margin-top: 34px;
  font-size: 1.5em;
  height: auto;
  font-weight: normal;
  font-family: "Tajawal", sans-serif;
}
.__vev_calendar-wrapper .events-wrapper {
  background-color: #73c1a5e8 !important;
}
.__vev_calendar-wrapper .cal-wrapper .cal-body .dates .item .is-event {
  border-color: #cacaca !important;
}
.__vev_calendar-wrapper .cal-wrapper .cal-body .dates .item .date-num {
  color: #3b3b3b !important;
}
.__vev_calendar-wrapper
  .cal-wrapper
  .cal-body
  .dates
  .item.selected-day
  .is-event {
  background: #73c1a5e8 !important;
}
.__vev_calendar-wrapper
  .cal-wrapper
  .cal-body
  .dates
  .item.selected-day
  .date-num {
  color: #fff !important;
  font-weight: 900;
}

.__vev_calendar-wrapper .events-wrapper .date {
  max-width: 100%;
}
</style>
